using CharacterGen.CharacterClasses;
using EncounterGen.Common;
using EncounterGen.Domain.Selectors;
using NUnit.Framework;

namespace EncounterGen.Tests.Integration.Tables.Creatures.EncounterGroups
{
    [TestFixture]
    public class EnvironmentEncounterGroupsTests : EncounterGroupsTests
    {
        [Test]
        public override void EntriesAreComplete()
        {
            AssertEncounterGroupEntriesAreComplete();
        }

        [Test]
        public void DungeonEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Dragonne, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragonne, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragonne, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.UmberHulk, RollConstants.One),
                FormatEncounter(CreatureConstants.UmberHulk, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.UmberHulk_TrulyHorrid, RollConstants.One),
                FormatEncounter(CreatureConstants.Drider, RollConstants.One),
                FormatEncounter(CreatureConstants.Drider, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Drider, RollConstants.OneD2,
                    CreatureConstants.Spider_Monstrous_Medium, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD6Plus3,
                    CreatureConstants.Giant_Stone_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD4Plus10,
                    CreatureConstants.Giant_Stone_Elder, RollConstants.OneD3,
                    CreatureConstants.Bear_Dire, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Tiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Gynosphinx, RollConstants.One),
                FormatEncounter(CreatureConstants.Gynosphinx, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Destrachan, RollConstants.One),
                FormatEncounter(CreatureConstants.Destrachan, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.PurpleWorm, RollConstants.One),
                FormatEncounter(CreatureConstants.MindFlayer, RollConstants.One),
                FormatEncounter(CreatureConstants.MindFlayer, RollConstants.One,
                    CreatureConstants.CharmedCreature + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.MindFlayer, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.MindFlayer, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Giant_Cloud, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Cloud, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Cloud, RollConstants.OneD3Plus1,
                    CreatureConstants.Griffon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Cloud, RollConstants.OneD3Plus1,
                    CreatureConstants.Lion_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Giant_Cloud, RollConstants.OneD6Plus5,
                    CreatureConstants.Griffon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Cloud, RollConstants.OneD6Plus5,
                    CreatureConstants.Lion_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Yrthak, RollConstants.One),
                FormatEncounter(CreatureConstants.Yrthak, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Couatl, RollConstants.One),
                FormatEncounter(CreatureConstants.Couatl, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Couatl, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Roper, RollConstants.One),
                FormatEncounter(CreatureConstants.Roper, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Roper, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Giant_Storm, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Storm, RollConstants.OneD3Plus1,
                    CreatureConstants.Roc, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Giant_Storm, RollConstants.OneD3Plus1,
                    CreatureConstants.Griffon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Darkmantle, RollConstants.One),
                FormatEncounter(CreatureConstants.Darkmantle, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Darkmantle, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Darkmantle, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Darkmantle, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Krenshar, RollConstants.One),
                FormatEncounter(CreatureConstants.Krenshar, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Krenshar, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD4Plus10,
                    CreatureConstants.Weasel_Dire, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD4Plus10,
                    CreatureConstants.Weasel_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Ant_Giant_Worker, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Ant_Giant_Soldier, RollConstants.One),
                FormatEncounter(CreatureConstants.Ant_Giant_Soldier, RollConstants.One,
                    CreatureConstants.Ant_Giant_Worker, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Ant_Giant_Soldier, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Choker, RollConstants.One),
                FormatEncounter(CreatureConstants.Shrieker, RollConstants.One),
                FormatEncounter(CreatureConstants.Shrieker, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.VioletFungus, RollConstants.One),
                FormatEncounter(CreatureConstants.VioletFungus, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.VioletFungus, RollConstants.OneD3Plus1,
                    CreatureConstants.Shrieker, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Lizardfolk, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Lizardfolk, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lizardfolk, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Badger, RollConstants.One),
                FormatEncounter(CreatureConstants.Badger, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Badger, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Badger_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Badger_Dire, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.GelatinousCube, RollConstants.One),
                FormatEncounter(CreatureConstants.PrayingMantis_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.BlackPudding, RollConstants.One),
                FormatEncounter(CreatureConstants.BlackPudding_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.PhantomFungus, RollConstants.One),
                FormatEncounter(CreatureConstants.Bugbear, RollConstants.One),
                FormatEncounter(CreatureConstants.Bugbear, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Bugbear, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Troglodyte, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Troglodyte, RollConstants.OneD6Plus5,
                    CreatureConstants.Lizard_Monitor, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ankheg, RollConstants.One),
                FormatEncounter(CreatureConstants.Ankheg, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Weasel, RollConstants.One),
                FormatEncounter(CreatureConstants.Weasel_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Weasel_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ooze_Gray, RollConstants.One),
                FormatEncounter(CreatureConstants.Ooze_OchreJelly, RollConstants.One),
                FormatEncounter(CreatureConstants.CarrionCrawler, RollConstants.One),
                FormatEncounter(CreatureConstants.CarrionCrawler, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.CarrionCrawler, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.RustMonster, RollConstants.One),
                FormatEncounter(CreatureConstants.RustMonster, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ettercap, RollConstants.One),
                FormatEncounter(CreatureConstants.Ettercap, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ettercap, RollConstants.OneD2,
                    CreatureConstants.Spider_Monstrous_Medium, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Wolverine, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolverine_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolverine_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Snake_Constrictor, RollConstants.One),
                FormatEncounter(CreatureConstants.Snake_Constrictor_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.GreenHag, RollConstants.One),
                FormatEncounter(CreatureConstants.GreenHag, RollConstants.OneD3Plus1,
                    CreatureConstants.Ogre, RollConstants.OneD4Plus2,
                    CreatureConstants.Giant_Hill, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.GreenHag, RollConstants.OneD3,
                    CreatureConstants.Annis, RollConstants.One,
                    CreatureConstants.Ogre, RollConstants.OneD4Plus2,
                    CreatureConstants.Giant_Hill, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Annis, RollConstants.OneD3,
                    CreatureConstants.GreenHag, RollConstants.One,
                    CreatureConstants.Ogre, RollConstants.OneD4Plus2,
                    CreatureConstants.Giant_Hill, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.BlinkDog, RollConstants.One),
                FormatEncounter(CreatureConstants.BlinkDog, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.BlinkDog, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Grick, RollConstants.One),
                FormatEncounter(CreatureConstants.Grick, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.ShockerLizard, RollConstants.One),
                FormatEncounter(CreatureConstants.ShockerLizard, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.ShockerLizard, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.ShockerLizard, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Worg, RollConstants.One),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Ape_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Ape_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.StagBeetle_Giant, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.StagBeetle_Giant, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Owlbear, RollConstants.One),
                FormatEncounter(CreatureConstants.Owlbear, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Owlbear, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.ShamblingMound, RollConstants.One),
                FormatEncounter(CreatureConstants.Wereboar, RollConstants.One),
                FormatEncounter(CreatureConstants.Wereboar, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wereboar, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Wereboar, RollConstants.OneD3Plus1,
                    CreatureConstants.Boar, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD3Plus1,
                    CreatureConstants.Wolf, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.One),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.DisplacerBeast, RollConstants.One),
                FormatEncounter(CreatureConstants.DisplacerBeast, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.DisplacerBeast, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Otyugh, RollConstants.One),
                FormatEncounter(CreatureConstants.Otyugh, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Otyugh, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Ettin, RollConstants.One),
                FormatEncounter(CreatureConstants.Ettin, RollConstants.OneD2,
                    CreatureConstants.Bear_Brown, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ettin, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Ettin, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ettin, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD2,
                    CreatureConstants.Goblin, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Ettin, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD2,
                    CreatureConstants.Orc, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Criosphinx, RollConstants.One),
                FormatEncounter(CreatureConstants.Boar_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Boar_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Aranea, RollConstants.One),
                FormatEncounter(CreatureConstants.Aranea, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Cloaker, RollConstants.One),
                FormatEncounter(CreatureConstants.Cloaker, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Cloaker, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Minotaur, RollConstants.One),
                FormatEncounter(CreatureConstants.Minotaur, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Minotaur, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Bat_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Bat_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Girallon, RollConstants.One),
                FormatEncounter(CreatureConstants.Girallon, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Hieracosphinx, RollConstants.One),
                FormatEncounter(CreatureConstants.Hieracosphinx, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Hieracosphinx, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.One),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Delver, RollConstants.One),
                FormatEncounter(CreatureConstants.WillOWisp, RollConstants.One),
                FormatEncounter(CreatureConstants.WillOWisp, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.WillOWisp, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Wyvern, RollConstants.One),
                FormatEncounter(CreatureConstants.Wyvern, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wyvern, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD6Plus3,
                    CreatureConstants.Wolf_Dire, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD4Plus10,
                    CreatureConstants.Wolf_Dire, RollConstants.OneD4Plus10,
                    CreatureConstants.Ogre, RollConstants.OneD3Plus1,
                    CreatureConstants.Orc, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Cryohydra_10Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_11Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_12Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_5Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_6Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_7Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_8Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_9Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_10Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_11Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_12Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_5Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_6Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_7Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_8Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_9Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_10Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_11Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_12Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_5Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_6Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_7Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_8Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_9Heads, RollConstants.One),
            };

            base.DistinctCollection(EnvironmentConstants.Dungeon, encounters);
        }

        [Test]
        public void CivilizedEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Dog, RollConstants.One),
                FormatEncounter(CreatureConstants.Dog, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Cat, RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[1]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[1]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[1]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[2]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[2]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[2]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[2]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[3]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[3]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[3]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[3]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[4]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[4]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[4]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[4]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[5]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[5]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[5]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[5]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[6]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[6]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[6]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[6]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[7]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[7]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[7]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[7]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[8]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[8]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[8]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[8]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[9]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[9]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[9]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[9]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[10]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[10]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[10]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[10]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[11]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[11]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[11]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[11]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[12]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[12]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[12]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[12]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[13]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[13]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[13]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[13]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[14]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[14]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[14]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[14]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[15]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[15]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[15]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[15]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[16]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[16]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[16]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[16]", RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Character + "[17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[17]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[17]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[17]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[18]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[18]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[18]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Character + "[19]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[19]", RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Character + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[18]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[18]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[18]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+1]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+3]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+5]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+7]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+9]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+11]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+13]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+15]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[1d2+17]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Farmer + "[20]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+1]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+3]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+5]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+7]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+9]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+11]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+13]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+15]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[1d2+17]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Herder + "[20]", RollConstants.OneD3,
                    CreatureConstants.Livestock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+1]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+3]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+5]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+7]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+9]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+11]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+13]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+15]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[1d2+17]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Hunter + "[20]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Hunter + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+1]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+1]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+3]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+3]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+5]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+5]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+7]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+7]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+9]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+9]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+11]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+11]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+13]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+13]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+15]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+15]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[1d2+17]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[1d2+17]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Merchant + "[20]", RollConstants.OneD3,
                    CreatureConstants.Warrior_Guard + "[20]", RollConstants.OneD3,
                    CreatureConstants.Expert_Merchant + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+3]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+5]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+7]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+9]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+11]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+13]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+15]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+17]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[20]", RollConstants.OneD6Plus3,
                    CreatureConstants.Expert_Minstrel + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+3]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+5]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+7]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+9]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+11]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+13]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+15]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[1d2+17]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Minstrel + "[20]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Bard + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+1]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+3]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+5]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+7]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+9]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+11]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+13]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+15]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+17]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_Captain + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+3]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+5]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+7]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+9]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+11]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+13]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+15]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[1d2+17]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Patrol + "[20]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Fighter + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+1]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+3]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+5]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+7]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+9]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+11]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+13]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+15]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+17]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+3]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+5]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+7]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+9]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+11]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+13]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+15]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+17]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[20]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+1]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+3]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+3]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+5]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+5]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+7]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+7]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+9]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+9]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+11]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+11]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+13]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+13]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+15]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+15]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+17]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+17]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[20]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[20]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+1]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+1]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+3]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+3]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+5]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+5]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+7]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+7]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+9]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+9]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+11]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+11]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+13]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+13]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+15]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+15]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+17]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[1d2+17]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[20]", RollConstants.OneD4Plus10,
                    CreatureConstants.Warrior_Guard + "[20]", RollConstants.OneD3Plus1,
                    CharacterClassConstants.Cleric + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[20]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_BanditLeader + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[20]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[20]", RollConstants.OneD4Plus10,
                    CharacterClassConstants.Fighter + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+1]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+3]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+5]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+7]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+9]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+11]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+13]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+15]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+17]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[20]", RollConstants.OneD3),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+3]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+5]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+7]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+9]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+11]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+13]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+15]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+17]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[20]", RollConstants.OneD3Plus1),
            };

            base.DistinctCollection(EnvironmentConstants.Civilized, encounters);
        }

        [Test]
        public void DesertEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Lamia, RollConstants.One),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Mummy, RollConstants.One),
                FormatEncounter(CreatureConstants.Mummy, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Mummy, RollConstants.OneD6Plus5),
            };

            base.DistinctCollection(EnvironmentConstants.Desert, encounters);
        }

        [Test]
        public void MountainEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Eagle, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.UmberHulk, RollConstants.One),
                FormatEncounter(CreatureConstants.UmberHulk, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.UmberHulk_TrulyHorrid, RollConstants.One),
                FormatEncounter(CreatureConstants.Drider, RollConstants.One),
                FormatEncounter(CreatureConstants.Drider, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Drider, RollConstants.OneD2,
                    CreatureConstants.Spider_Monstrous_Medium, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD6Plus3,
                    CreatureConstants.Giant_Stone_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Stone, RollConstants.OneD4Plus10,
                    CreatureConstants.Giant_Stone_Elder, RollConstants.OneD3,
                    CreatureConstants.Bear_Dire, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD6Plus3,
                    CreatureConstants.Wolf_Dire, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD4Plus10,
                    CreatureConstants.Wolf_Dire, RollConstants.OneD4Plus10,
                    CreatureConstants.Ogre, RollConstants.OneD3Plus1,
                    CreatureConstants.Orc, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Grimlock, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Grimlock, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Tiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Troglodyte, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Troglodyte, RollConstants.OneD6Plus5,
                    CreatureConstants.Lizard_Monitor, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.One),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD3Plus1,
                    CreatureConstants.Wolf, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Worg, RollConstants.One),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Yrthak, RollConstants.One),
                FormatEncounter(CreatureConstants.Yrthak, RollConstants.OneD3Plus1),
            };

            base.DistinctCollection(EnvironmentConstants.Mountain, encounters);
        }

        [Test]
        public void HillsEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Eagle, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD6Plus3,
                    CreatureConstants.Wolf_Dire, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Hill, RollConstants.OneD4Plus10,
                    CreatureConstants.Wolf_Dire, RollConstants.OneD4Plus10,
                    CreatureConstants.Ogre, RollConstants.OneD3Plus1,
                    CreatureConstants.Orc, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.One),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lamia, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Tiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.One),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD3Plus1,
                    CreatureConstants.Wolf, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Worg, RollConstants.One),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Yrthak, RollConstants.One),
                FormatEncounter(CreatureConstants.Yrthak, RollConstants.OneD3Plus1),
            };

            base.DistinctCollection(EnvironmentConstants.Hills, encounters);
        }

        [Test]
        public void MarshEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.BlackPudding, RollConstants.One),
                FormatEncounter(CreatureConstants.BlackPudding_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_10Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_11Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_12Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_5Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_6Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_7Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_8Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Cryohydra_9Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_10Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_11Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_12Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_5Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_6Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_7Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_8Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Hydra_9Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Ooze_Gray, RollConstants.One),
                FormatEncounter(CreatureConstants.Ooze_OchreJelly, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_10Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_11Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_12Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_5Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_6Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_7Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_8Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.Pyrohydra_9Heads, RollConstants.One),
                FormatEncounter(CreatureConstants.WillOWisp, RollConstants.One),
                FormatEncounter(CreatureConstants.WillOWisp, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.WillOWisp, RollConstants.OneD3Plus1),
            };

            base.DistinctCollection(EnvironmentConstants.Marsh, encounters);
        }

        [Test]
        public void ForestEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Eagle, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Grig, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Grig, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD4Plus10,
                    CreatureConstants.Weasel_Dire, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Kobold, RollConstants.OneD4Plus10,
                    CreatureConstants.Weasel_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Pixie, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Pixie, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Stirge, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Stirge, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Stirge, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Tiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Treant, RollConstants.One),
                FormatEncounter(CreatureConstants.Treant, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.One),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD3Plus1,
                    CreatureConstants.Wolf, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Worg, RollConstants.One),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD6Plus5),
            };

            base.DistinctCollection(EnvironmentConstants.Forest, encounters);
        }

        [Test]
        public void PlainsEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Brown, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Bear_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lion_Dire, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Tiger_Dire, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Eagle, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Eagle_Giant, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.One),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Owl_Giant, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Tiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.One),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Werebear, RollConstants.OneD3Plus1,
                    CreatureConstants.Bear_Brown, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.One),
                FormatEncounter(CreatureConstants.Weretiger, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Werewolf, RollConstants.OneD3Plus1,
                    CreatureConstants.Wolf, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.One),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wolf, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Worg, RollConstants.One),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Worg, RollConstants.OneD6Plus5),
            };

            base.DistinctCollection(EnvironmentConstants.Plains, encounters);
        }
    }
}
