using CharacterGen.CharacterClasses;
using EncounterGen.Common;
using EncounterGen.Domain.Selectors;
using EncounterGen.Domain.Tables;
using NUnit.Framework;

namespace EncounterGen.Tests.Integration.Tables.Creatures.EncounterGroups
{
    [TestFixture]
    public class GeneralEncounterGroupsTests : EncounterGroupsTests
    {
        [Test]
        public override void EntriesAreComplete()
        {
            AssertEncounterGroupEntriesAreComplete();
        }

        [Test]
        public void MagicEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Achaierai, RollConstants.One),
                FormatEncounter(CreatureConstants.Achaierai, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Allip, RollConstants.One),
                FormatEncounter(CreatureConstants.AnimatedObject_Colossal, RollConstants.One),
                FormatEncounter(CreatureConstants.AnimatedObject_Gargantuan, RollConstants.One),
                FormatEncounter(CreatureConstants.AnimatedObject_Huge, RollConstants.One),
                FormatEncounter(CreatureConstants.AnimatedObject_Large, RollConstants.One),
                FormatEncounter(CreatureConstants.AnimatedObject_Medium, RollConstants.One),
                FormatEncounter(CreatureConstants.AnimatedObject_Small, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.AnimatedObject_Tiny, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Arrowhawk_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Arrowhawk_Adult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Arrowhawk_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Arrowhawk_Elder, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Arrowhawk_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Arrowhawk_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.AstralDeva, RollConstants.One),
                FormatEncounter(CreatureConstants.AstralDeva, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.AstralDeva, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Avoral, RollConstants.One),
                FormatEncounter(CreatureConstants.Avoral, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Avoral, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Azer, RollConstants.One),
                FormatEncounter(CreatureConstants.Azer, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Azer, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Babau, RollConstants.One),
                FormatEncounter(CreatureConstants.Babau, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Balor, RollConstants.One),
                FormatEncounter(CreatureConstants.Balor, RollConstants.One,
                    CreatureConstants.Marilith, RollConstants.One,
                    CreatureConstants.Hezrou, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.BeardedDevil_Barbazu, RollConstants.One),
                FormatEncounter(CreatureConstants.BeardedDevil_Barbazu, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.BeardedDevil_Barbazu, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.BeardedDevil_Barbazu, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Barghest, RollConstants.One),
                FormatEncounter(CreatureConstants.Barghest, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Barghest_Greater, RollConstants.One),
                FormatEncounter(CreatureConstants.Barghest_Greater, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Bebilith, RollConstants.One),
                FormatEncounter(CreatureConstants.Belker, RollConstants.One),
                FormatEncounter(CreatureConstants.Belker, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Belker, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Bodak, RollConstants.One),
                FormatEncounter(CreatureConstants.Bodak, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.CelestialCreature, RollConstants.One),
                FormatEncounter(CreatureConstants.ChaosBeast, RollConstants.One),
                FormatEncounter(CreatureConstants.HornedDevil_Cornugon, RollConstants.One),
                FormatEncounter(CreatureConstants.HornedDevil_Cornugon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.HornedDevil_Cornugon, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Devourer, RollConstants.One),
                FormatEncounter(CreatureConstants.Djinni, RollConstants.One),
                FormatEncounter(CreatureConstants.Djinni, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Djinni, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Djinni_Noble, RollConstants.One),
                FormatEncounter(CreatureConstants.Dretch, RollConstants.One),
                FormatEncounter(CreatureConstants.Dretch, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dretch, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dretch, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dretch, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Efreeti, RollConstants.One),
                FormatEncounter(CreatureConstants.Efreeti, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Efreeti, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Elemental_Air_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Earth_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Fire_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Water_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Air_Greater, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Earth_Greater, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Fire_Greater, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Water_Greater, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Air_Huge, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Earth_Huge, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Fire_Huge, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Water_Huge, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Air_Large, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Earth_Large, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Fire_Large, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Water_Large, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Air_Medium, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Earth_Medium, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Fire_Medium, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Water_Medium, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Air_Small, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Earth_Small, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Fire_Small, RollConstants.One),
                FormatEncounter(CreatureConstants.Elemental_Water_Small, RollConstants.One),
                FormatEncounter(CreatureConstants.Erinyes, RollConstants.One),
                FormatEncounter(CreatureConstants.EtherealFilcher, RollConstants.One),
                FormatEncounter(CreatureConstants.EtherealMarauder, RollConstants.One),
                FormatEncounter(CreatureConstants.FiendishCreature, RollConstants.One),
                FormatEncounter(CreatureConstants.FormianMyrmarch, RollConstants.One),
                FormatEncounter(CreatureConstants.FormianMyrmarch, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.FormianMyrmarch, RollConstants.One,
                    CreatureConstants.FormianWarrior, RollConstants.OneD6Plus5,
                    CreatureConstants.FormianWorker, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.FormianTaskmaster, RollConstants.One,
                    CreatureConstants.DominatedCreature + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.FormianTaskmaster, RollConstants.OneD3Plus1,
                    CreatureConstants.DominatedCreature + "[4]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.FormianWarrior, RollConstants.One),
                FormatEncounter(CreatureConstants.FormianWarrior, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.FormianWarrior, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.FormianWorker, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.FormianWorker, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.FormianQueen, RollConstants.One,
                    CreatureConstants.FormianWorker, RollConstants.OneD4Plus10,
                    CreatureConstants.FormianWarrior, RollConstants.OneD4Plus10,
                    CreatureConstants.FormianTaskmaster, RollConstants.OneD4Plus2,
                    CreatureConstants.DominatedCreature + "[4]", RollConstants.OneD4Plus2,
                    CreatureConstants.FormianMyrmarch, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.IceDevil_Gelugon, RollConstants.One),
                FormatEncounter(CreatureConstants.IceDevil_Gelugon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.IceDevil_Gelugon, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.IceDevil_Gelugon, RollConstants.OneD2,
                    CreatureConstants.BoneDevil_Osyluth, RollConstants.OneD3Plus1,
                    CreatureConstants.BeardedDevil_Barbazu, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Ghaele, RollConstants.One),
                FormatEncounter(CreatureConstants.Ghaele, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ghaele, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Ghast, RollConstants.One),
                FormatEncounter(CreatureConstants.Ghast, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Ghast, RollConstants.OneD3Plus1,
                    CreatureConstants.Ghoul, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Ghost + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[18]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[19]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[21]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[22]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[23]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[24]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[25]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[26]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghost + "[27]", RollConstants.One),
                FormatEncounter(CreatureConstants.Ghoul, RollConstants.One),
                FormatEncounter(CreatureConstants.Ghoul, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Ghoul, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Glabrezu, RollConstants.One),
                FormatEncounter(CreatureConstants.Glabrezu, RollConstants.One,
                    CreatureConstants.Succubus, RollConstants.One,
                    CreatureConstants.Vrock, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Golem_Clay, RollConstants.One),
                FormatEncounter(CreatureConstants.Golem_Clay, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Golem_Flesh, RollConstants.One),
                FormatEncounter(CreatureConstants.Golem_Flesh, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Golem_Iron, RollConstants.One),
                FormatEncounter(CreatureConstants.Golem_Iron, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Golem_Stone, RollConstants.One),
                FormatEncounter(CreatureConstants.Golem_Stone, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Golem_Stone_Greater, RollConstants.One),
                FormatEncounter(CreatureConstants.Golem_Stone_Greater, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.BarbedDevil_Hamatula, RollConstants.One),
                FormatEncounter(CreatureConstants.BarbedDevil_Hamatula, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.BarbedDevil_Hamatula, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.BarbedDevil_Hamatula, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Hellcat_Bezekira, RollConstants.One),
                FormatEncounter(CreatureConstants.Hellcat_Bezekira, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Hellcat_Bezekira, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.HellHound, RollConstants.One),
                FormatEncounter(CreatureConstants.HellHound, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.HellHound, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Hezrou, RollConstants.One),
                FormatEncounter(CreatureConstants.Hezrou, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Homunculus, RollConstants.One),
                FormatEncounter(CreatureConstants.HoundArchon, RollConstants.One),
                FormatEncounter(CreatureConstants.HoundArchon, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.HoundArchon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Howler, RollConstants.One),
                FormatEncounter(CreatureConstants.Howler, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Howler, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Imp, RollConstants.One),
                FormatEncounter(CreatureConstants.InvisibleStalker, RollConstants.One),
                FormatEncounter(CreatureConstants.Janni, RollConstants.One),
                FormatEncounter(CreatureConstants.Janni, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Janni, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.ChainDevil_Kyton, RollConstants.One),
                FormatEncounter(CreatureConstants.ChainDevil_Kyton, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.ChainDevil_Kyton, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.ChainDevil_Kyton, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.LanternArchon, RollConstants.One),
                FormatEncounter(CreatureConstants.LanternArchon, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.LanternArchon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Lemure, RollConstants.One),
                FormatEncounter(CreatureConstants.Lemure, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Lemure, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Lemure, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Lemure, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Lich + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[18]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[19]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[21]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[22]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[23]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[24]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[25]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[26]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lich + "[27]", RollConstants.One),
                FormatEncounter(CreatureConstants.Lillend, RollConstants.One),
                FormatEncounter(CreatureConstants.Lillend, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Magmin, RollConstants.One),
                FormatEncounter(CreatureConstants.Magmin, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Magmin, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Marilith, RollConstants.One),
                FormatEncounter(CreatureConstants.Marilith, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Mephit, RollConstants.One),
                FormatEncounter(CreatureConstants.Mephit, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Mephit, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Mohrg, RollConstants.One),
                FormatEncounter(CreatureConstants.Mohrg, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Mohrg, RollConstants.OneD3Plus1,
                    CreatureConstants.Zombie_Human, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Nalfeshnee, RollConstants.One),
                FormatEncounter(CreatureConstants.Nalfeshnee, RollConstants.One,
                    CreatureConstants.Hezrou, RollConstants.One,
                    CreatureConstants.Vrock, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NessianWarhound, RollConstants.One),
                FormatEncounter(CreatureConstants.NessianWarhound, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.NessianWarhound, RollConstants.OneD2,
                    CreatureConstants.HellHound, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Nightcrawler, RollConstants.One),
                FormatEncounter(CreatureConstants.Nightcrawler, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.NightHag, RollConstants.One),
                FormatEncounter(CreatureConstants.NightHag, RollConstants.One,
                    CreatureConstants.Nightmare, RollConstants.One),
                FormatEncounter(CreatureConstants.NightHag, RollConstants.OneD3,
                    CreatureConstants.Nightmare, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Nightmare, RollConstants.One),
                FormatEncounter(CreatureConstants.Nightmare_Cauchemar, RollConstants.One),
                FormatEncounter(CreatureConstants.Nightwalker, RollConstants.One),
                FormatEncounter(CreatureConstants.Nightwalker, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Nightwalker, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Nightwing, RollConstants.One),
                FormatEncounter(CreatureConstants.Nightwing, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Nightwing, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.BoneDevil_Osyluth, RollConstants.One),
                FormatEncounter(CreatureConstants.BoneDevil_Osyluth, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.BoneDevil_Osyluth, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.PhaseSpider, RollConstants.One),
                FormatEncounter(CreatureConstants.PhaseSpider, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.PitFiend, RollConstants.One),
                FormatEncounter(CreatureConstants.PitFiend, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.PitFiend, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.PitFiend, RollConstants.OneD2,
                    CreatureConstants.HornedDevil_Cornugon, RollConstants.OneD3Plus1,
                    CreatureConstants.BarbedDevil_Hamatula, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Planetar, RollConstants.One),
                FormatEncounter(CreatureConstants.Planetar, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Quasit, RollConstants.One),
                FormatEncounter(CreatureConstants.Rast, RollConstants.One),
                FormatEncounter(CreatureConstants.Rast, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Rast, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Colossal, RollConstants.One),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Gargantuan, RollConstants.One),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Huge, RollConstants.One),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Large, RollConstants.One),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Medium, RollConstants.One),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Small, RollConstants.One),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Small, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Tiny, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Ravid, RollConstants.One,
                    CreatureConstants.AnimatedObject_Tiny, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Retriever, RollConstants.One),
                FormatEncounter(CreatureConstants.Salamander_Average, RollConstants.One),
                FormatEncounter(CreatureConstants.Salamander_Average, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Salamander_Average, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Salamander_Flamebrother, RollConstants.One),
                FormatEncounter(CreatureConstants.Salamander_Flamebrother, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Salamander_Flamebrother, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Salamander_Noble, RollConstants.One),
                FormatEncounter(CreatureConstants.Salamander_Noble, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Salamander_Noble, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Shadow, RollConstants.One),
                FormatEncounter(CreatureConstants.Shadow, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Shadow, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Shadow_Greater, RollConstants.One),
                FormatEncounter(CreatureConstants.ShadowMastiff, RollConstants.One),
                FormatEncounter(CreatureConstants.ShadowMastiff, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.ShadowMastiff, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Skeleton, RollConstants.One),
                FormatEncounter(CreatureConstants.Slaad_Blue, RollConstants.One),
                FormatEncounter(CreatureConstants.Slaad_Blue, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Slaad_Blue, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Slaad_Blue, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Slaad_Death, RollConstants.One),
                FormatEncounter(CreatureConstants.Slaad_Death, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Slaad_Gray, RollConstants.One),
                FormatEncounter(CreatureConstants.Slaad_Gray, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Slaad_Green, RollConstants.One),
                FormatEncounter(CreatureConstants.Slaad_Green, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Slaad_Red, RollConstants.One),
                FormatEncounter(CreatureConstants.Slaad_Red, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Slaad_Red, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Slaad_Red, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Solar, RollConstants.One),
                FormatEncounter(CreatureConstants.Solar, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Spectre, RollConstants.One),
                FormatEncounter(CreatureConstants.Spectre, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Spectre, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Succubus, RollConstants.One),
                FormatEncounter(CreatureConstants.Thoqqua, RollConstants.One),
                FormatEncounter(CreatureConstants.Thoqqua, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.TrumpetArchon, RollConstants.One),
                FormatEncounter(CreatureConstants.TrumpetArchon, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.TrumpetArchon, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Vampire + "[1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[14]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[16]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[18]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[19]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[21]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[22]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[23]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[24]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[25]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[26]", RollConstants.One),
                FormatEncounter(CreatureConstants.Vampire + "[27]", RollConstants.One),
                FormatEncounter(CreatureConstants.VampireSpawn, RollConstants.One),
                FormatEncounter(CreatureConstants.VampireSpawn, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Vrock, RollConstants.One),
                FormatEncounter(CreatureConstants.Vrock, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Vrock, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Vrock, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Wight, RollConstants.One),
                FormatEncounter(CreatureConstants.Wight, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wight, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Wight, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Wraith, RollConstants.One),
                FormatEncounter(CreatureConstants.Wraith, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Wraith, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Wraith_Dread, RollConstants.One),
                FormatEncounter(CreatureConstants.Xill, RollConstants.One),
                FormatEncounter(CreatureConstants.Xill, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Xorn_Average, RollConstants.One),
                FormatEncounter(CreatureConstants.Xorn_Average, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Xorn_Average, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Xorn_Elder, RollConstants.One),
                FormatEncounter(CreatureConstants.Xorn_Elder, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Xorn_Elder, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Xorn_Minor, RollConstants.One),
                FormatEncounter(CreatureConstants.Xorn_Minor, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Xorn_Minor, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.YethHound, RollConstants.One),
                FormatEncounter(CreatureConstants.YethHound, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.YethHound, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Zombie, RollConstants.One),
                FormatEncounter(CreatureConstants.Bralani, RollConstants.One),
                FormatEncounter(CreatureConstants.Bralani, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Bralani, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Kolyarut, RollConstants.One),
                FormatEncounter(CreatureConstants.Marut, RollConstants.One),
                FormatEncounter(CreatureConstants.Zelekhut, RollConstants.One),
                FormatEncounter(CreatureConstants.Leonal, RollConstants.One),
                FormatEncounter(CreatureConstants.Leonal, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.ShieldGuardian, RollConstants.One),
                FormatEncounter(CreatureConstants.Titan, RollConstants.One),
                FormatEncounter(CreatureConstants.Titan, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Basilisk_AbyssalGreater, RollConstants.One),
                FormatEncounter(CreatureConstants.Basilisk_AbyssalGreater, RollConstants.OneD4Plus2),
            };

            base.DistinctCollection(GroupConstants.Magic, encounters);
        }

        [Test]
        public void LandEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Annis, RollConstants.One),
                FormatEncounter(CreatureConstants.Annis, RollConstants.One,
                    CreatureConstants.GreenHag, RollConstants.One,
                    CreatureConstants.SeaHag, RollConstants.One,
                    CreatureConstants.Ogre, RollConstants.OneD3,
                    CreatureConstants.Giant_Hill, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Annis, RollConstants.One,
                    CreatureConstants.GreenHag, RollConstants.One,
                    CreatureConstants.SeaHag, RollConstants.One,
                    CreatureConstants.Ogre, RollConstants.OneD6Plus3,
                    CreatureConstants.Giant_Hill, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Basilisk, RollConstants.One),
                FormatEncounter(CreatureConstants.Basilisk, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Behir, RollConstants.One),
                FormatEncounter(CreatureConstants.Behir, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Beholder, RollConstants.One),
                FormatEncounter(CreatureConstants.Beholder, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Beholder, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Beholder, RollConstants.One,
                    CreatureConstants.CharmedCreature + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Character + "[1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[2]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[3]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[4]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[5]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[6]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[7]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[8]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[9]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[10]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[11]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[12]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[13]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[14]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[15]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[16]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[17]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[18]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[19]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[20]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[21]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[22]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[23]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[24]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[25]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Character + "[26]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Chimera, RollConstants.One),
                FormatEncounter(CreatureConstants.Chimera, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Chimera, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Chuul, RollConstants.One),
                FormatEncounter(CreatureConstants.Chuul, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Chuul, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+1]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+3]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+5]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+7]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+9]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+11]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+13]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+15]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+17]", RollConstants.OneD4Plus2,
                    CharacterClassConstants.Adept + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+1]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+3]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+5]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+7]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+9]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+11]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+13]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+15]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+17]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[20]", RollConstants.OneD6Plus3,
                    CharacterClassConstants.Cleric + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+1]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+1]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+3]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+3]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+5]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+5]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+7]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+7]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+9]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+9]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+11]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+11]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+13]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+13]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+15]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+15]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[1d2+17]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[1d2+17]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Commoner_Pilgrim + "[20]", RollConstants.OneD6Plus3,
                    CreatureConstants.Warrior_Guard + "[20]", RollConstants.OneD3,
                    CharacterClassConstants.Cleric + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Dog, RollConstants.One),
                FormatEncounter(CreatureConstants.Dog, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Doppelganger, RollConstants.One),
                FormatEncounter(CreatureConstants.Doppelganger, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Doppelganger, RollConstants.OneD4Plus2),
                FormatEncounter(CreatureConstants.Gargoyle, RollConstants.One),
                FormatEncounter(CreatureConstants.Gargoyle, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Gargoyle, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Giant_Fire, RollConstants.One),
                FormatEncounter(CreatureConstants.Giant_Fire, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Giant_Fire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Giant_Fire, RollConstants.OneD6Plus3,
                    CreatureConstants.HellHound, RollConstants.OneD3Plus1,
                    CreatureConstants.Troll, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Giant_Fire, RollConstants.OneD6Plus3,
                    CreatureConstants.HellHound, RollConstants.OneD3Plus1,
                    CreatureConstants.Ettin, RollConstants.OneD3),
                FormatEncounter(CreatureConstants.Giant_Fire, RollConstants.OneD4Plus10,
                    CreatureConstants.HellHound, RollConstants.OneD4Plus10,
                    CreatureConstants.Troll, RollConstants.OneD4Plus10,
                    CreatureConstants.Ettin, RollConstants.OneD6Plus5,
                    CreatureConstants.Dragon_Red_Young, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.GibberingMouther, RollConstants.One),
                FormatEncounter(CreatureConstants.GrayRender, RollConstants.One),
                FormatEncounter(CreatureConstants.Medusa, RollConstants.One),
                FormatEncounter(CreatureConstants.Medusa, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Mimic, RollConstants.One),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+3]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+5]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+7]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+9]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+11]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+13]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+15]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[1d2+17]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.NPC_Traveler + "[20]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Nymph, RollConstants.One),
                FormatEncounter(CreatureConstants.Ogre, RollConstants.One),
                FormatEncounter(CreatureConstants.Ogre, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Ogre, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Ogre, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.OgreMage, RollConstants.One),
                FormatEncounter(CreatureConstants.OgreMage, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.OgreMage, RollConstants.OneD2,
                    CreatureConstants.Ogre, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Orc, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Orc, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Phasm, RollConstants.One),
                FormatEncounter(CreatureConstants.Rat, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Rat_Dire, RollConstants.One),
                FormatEncounter(CreatureConstants.Rat_Dire, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.Tarrasque, RollConstants.One),
                FormatEncounter(CreatureConstants.Troll, RollConstants.One),
                FormatEncounter(CreatureConstants.Troll, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Vargouille, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Vargouille, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[20]", RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+1]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+13]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+15]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[1d2+17]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD4Plus2,
                    CreatureConstants.Warrior_BanditLeader + "[20]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[2]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+1]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[3]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+3]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[4]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+5]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[5]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+7]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[6]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+9]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[7]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+11]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[8]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+13]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[9]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+15]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[10]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[1d2+17]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[11]", RollConstants.One),
                FormatEncounter(CreatureConstants.Warrior_Bandit + "[20]", RollConstants.OneD6Plus5,
                    CharacterClassConstants.Fighter + "[12]", RollConstants.One),
                FormatEncounter(CreatureConstants.Wererat, RollConstants.One),
                FormatEncounter(CreatureConstants.Wererat, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Wererat, RollConstants.OneD3Plus1,
                    CreatureConstants.Rat_Dire, RollConstants.OneD6Plus3),
                FormatEncounter(CreatureConstants.Wererat, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.ElfWarrior, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.ElfWarrior, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.DwarfWarrior, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.DwarfWarrior, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.HalflingWarrior, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.HalflingWarrior, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.HalflingWarrior, RollConstants.OneD4Plus10,
                    CreatureConstants.Dog, RollConstants.OneD6Plus5,
                    CreatureConstants.Dog_Riding, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.GnomeWarrior, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.GnomeWarrior, RollConstants.OneD4Plus10),
                FormatEncounter(CreatureConstants.GnomeWarrior, RollConstants.OneD4Plus10,
                    CreatureConstants.Badger_Dire, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.AasimarWarrior, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.TieflingWarrior, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.AasimarWarrior, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.TieflingWarrior, RollConstants.OneD3Plus1),
            };

            base.DistinctCollection(GroupConstants.Land, encounters);
        }

        [Test]
        public void DragonEncounters()
        {
            var encounters = new[]
            {
                FormatEncounter(CreatureConstants.Dragon_Black_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Black_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Black_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Black_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Black_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Black_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Black_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Black_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Black_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Black_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Black_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Black_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Black_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Black_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Black_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Black_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Black_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Black_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Black_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Black_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Blue_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Blue_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Blue_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Blue_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Blue_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Blue_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Blue_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Blue_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Blue_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Blue_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Blue_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Blue_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Blue_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Blue_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Blue_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Blue_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Blue_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Blue_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Blue_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Blue_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Green_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Green_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Green_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Green_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Green_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Green_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Green_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Green_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Green_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Green_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Green_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Green_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Green_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Green_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Green_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Green_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Green_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Green_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Green_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Green_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Red_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Red_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Red_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Red_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Red_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Red_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Red_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Red_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Red_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Red_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Red_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Red_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Red_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Red_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Red_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Red_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Red_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Red_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Red_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Red_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_White_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_White_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_White_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_White_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_White_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_White_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_White_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_White_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_White_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_White_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_White_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_White_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_White_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_White_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_White_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_White_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_White_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_White_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_White_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_White_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Brass_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Brass_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Brass_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Brass_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Brass_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Brass_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Brass_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Brass_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Brass_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Brass_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Brass_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Brass_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Brass_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Brass_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Brass_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Brass_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Brass_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Brass_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Brass_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Brass_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Bronze_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Bronze_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Bronze_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Bronze_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Bronze_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Bronze_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Bronze_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Bronze_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Bronze_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Bronze_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Bronze_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Bronze_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Bronze_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Bronze_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Bronze_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Copper_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Copper_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Copper_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Copper_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Copper_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Copper_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Copper_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Copper_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Copper_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Copper_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Copper_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Copper_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Copper_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Copper_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Copper_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Copper_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Copper_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Copper_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Copper_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Copper_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Gold_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Gold_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Gold_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Gold_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Gold_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Gold_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Gold_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Gold_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Gold_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Gold_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Gold_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Gold_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Gold_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Gold_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Gold_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Gold_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Gold_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Gold_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Gold_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Gold_VeryYoung, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Silver_Wyrmling, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_VeryYoung, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_Young, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_Juvenile, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_YoungAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_Adult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_Adult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Silver_Adult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Silver_Wyrmling, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_MatureAdult, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_MatureAdult, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Silver_MatureAdult, RollConstants.OneD2,
                    CreatureConstants.Dragon_Silver_VeryYoung, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_Old, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_Old, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Silver_Old, RollConstants.OneD2,
                    CreatureConstants.Dragon_Silver_Young, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_VeryOld, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_VeryOld, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Silver_VeryOld, RollConstants.OneD2,
                    CreatureConstants.Dragon_Silver_Juvenile, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_Ancient, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_Ancient, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Silver_Ancient, RollConstants.OneD2,
                    CreatureConstants.Dragon_Silver_YoungAdult, RollConstants.OneD3Plus1),
                FormatEncounter(CreatureConstants.Dragon_Silver_Wyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_Wyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Silver_Wyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Silver_Adult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Silver_Wyrmling, RollConstants.OneD6Plus5),
                FormatEncounter(CreatureConstants.Dragon_Silver_GreatWyrm, RollConstants.One),
                FormatEncounter(CreatureConstants.Dragon_Silver_GreatWyrm, RollConstants.OneD2),
                FormatEncounter(CreatureConstants.Dragon_Silver_GreatWyrm, RollConstants.OneD2,
                    CreatureConstants.Dragon_Silver_MatureAdult, RollConstants.OneD3Plus1,
                    CreatureConstants.Dragon_Silver_VeryYoung, RollConstants.OneD6Plus5),
            };

            base.DistinctCollection(GroupConstants.Dragon, encounters);
        }
    }
}
