using EncounterGen.Common;
using NUnit.Framework;

namespace EncounterGen.Tests.Unit.Common
{
    [TestFixture]
    public class CreatureConstantsTests
    {
        [TestCase(CreatureConstants.Allip, "Allip")]
        [TestCase(CreatureConstants.Ankheg, "Ankheg")]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, "Giant soldier ant")]
        [TestCase(CreatureConstants.Ant_Giant_Worker, "Giant worker ant")]
        [TestCase(CreatureConstants.AstralDeva, "Astral deva (celestial)")]
        [TestCase(CreatureConstants.Azer, "Azer")]
        [TestCase(CreatureConstants.Balor, "Balor (demon)")]
        [TestCase(CreatureConstants.Beholder, "Beholder")]
        [TestCase(CreatureConstants.BlinkDog, "Blink dog")]
        [TestCase(CreatureConstants.Boar_Dire, "Dire boar")]
        [TestCase(CreatureConstants.Bugbear, "Bugbear")]
        [TestCase(CreatureConstants.CarrionCrawler, "Carrion crawler")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, "Large monstrous centipede")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, "Medium monstrous centipede")]
        [TestCase(CreatureConstants.Character, "Character")]
        [TestCase(CreatureConstants.Choker, "Choker")]
        [TestCase(CreatureConstants.Cockatrice, "Cockatrice")]
        [TestCase(CreatureConstants.Cornugon, "Cornugon (devil)")]
        [TestCase(CreatureConstants.Cryohydra, "Cryohydra")]
        [TestCase(CreatureConstants.Darkmantle, "Darkmantle")]
        [TestCase(CreatureConstants.Doppelganger, "Doppelganger")]
        [TestCase(CreatureConstants.Dragon, "Dragon")]
        [TestCase(CreatureConstants.Dragon_Black_VeryOld, "Very old black dragon")]
        [TestCase(CreatureConstants.DwarfWarrior, "Dwarf warrior")]
        [TestCase(CreatureConstants.ElfWarrior, "Elf warrior")]
        [TestCase(CreatureConstants.EtherealMarauder, "Ethereal marauder")]
        [TestCase(CreatureConstants.Ettercap, "Ettercap")]
        [TestCase(CreatureConstants.FireBeetle_Giant, "Giant fire beetle")]
        [TestCase(CreatureConstants.FormianWarrior, "Formian warrior")]
        [TestCase(CreatureConstants.FormianWorker, "Formian worker")]
        [TestCase(CreatureConstants.Gelugon, "Gelugon (devil)")]
        [TestCase(CreatureConstants.Ghaele, "Ghaele (celestial)")]
        [TestCase(CreatureConstants.Ghast, "Ghast")]
        [TestCase(CreatureConstants.Ghost, "Ghost")]
        [TestCase(CreatureConstants.Ghoul, "Ghoul")]
        [TestCase(CreatureConstants.Giant_Cloud, "Cloud giant")]
        [TestCase(CreatureConstants.Giant_Frost, "Frost giant")]
        [TestCase(CreatureConstants.Giant_Storm, "Storm giant")]
        [TestCase(CreatureConstants.GibberingMouther, "Gibbering mouther")]
        [TestCase(CreatureConstants.Glabrezu, "Glabrezu (demon)")]
        [TestCase(CreatureConstants.Gnoll, "Gnoll")]
        [TestCase(CreatureConstants.Goblin, "Goblin")]
        [TestCase(CreatureConstants.Golem_Stone, "Stone golem")]
        [TestCase(CreatureConstants.Greenhag, "Greenhag")]
        [TestCase(CreatureConstants.Grick, "Grick")]
        [TestCase(CreatureConstants.Hamatula, "Hamatula (devil)")]
        [TestCase(CreatureConstants.Hezrou, "Hezrou (demon)")]
        [TestCase(CreatureConstants.Hobgoblin, "Hobgoblin")]
        [TestCase(CreatureConstants.Human, "Human")]
        [TestCase(CreatureConstants.Hydra, "Hydra")]
        [TestCase(CreatureConstants.Hyena, "Hyena")]
        [TestCase(CreatureConstants.Imp, "Imp (devil)")]
        [TestCase(CreatureConstants.Kobold, "Kobold")]
        [TestCase(CreatureConstants.Krenshar, "Krenshar")]
        [TestCase(CreatureConstants.LanternArchon, "Lantern archon (celestial)")]
        [TestCase(CreatureConstants.Lemure, "Lemure (devil)")]
        [TestCase(CreatureConstants.Lich, "Lich")]
        [TestCase(CreatureConstants.Lion_Dire, "Dire lion")]
        [TestCase(CreatureConstants.Lizard_Giant, "Giant lizard")]
        [TestCase(CreatureConstants.Lizardfolk, "Lizardfolk")]
        [TestCase(CreatureConstants.Magmin, "Magmin")]
        [TestCase(CreatureConstants.Marilith, "Marilith (demon)")]
        [TestCase(CreatureConstants.Mephit, "Mephit")]
        [TestCase(CreatureConstants.Mimic, "Mimic")]
        [TestCase(CreatureConstants.MindFlayer, "Mind flayer")]
        [TestCase(CreatureConstants.Mummy, "Mummy")]
        [TestCase(CreatureConstants.Naga_Spirit, "Spirit naga")]
        [TestCase(CreatureConstants.Nalfeshnee, "Nalfeshnee (demon)")]
        [TestCase(CreatureConstants.Nightcrawler, "Nightcrawler (nightshade)")]
        [TestCase(CreatureConstants.Nightmare, "Nightmare")]
        [TestCase(CreatureConstants.Nightwalker, "Nightwalker (nightshade)")]
        [TestCase(CreatureConstants.Ogre, "Ogre")]
        [TestCase(CreatureConstants.Ooze_Gray, "Gray ooze")]
        [TestCase(CreatureConstants.Ooze_OchreJelly, "Ochre jelly")]
        [TestCase(CreatureConstants.Orc, "Orc")]
        [TestCase(CreatureConstants.PitFiend, "Pit fiend (devil)")]
        [TestCase(CreatureConstants.Planetar, "Planetar (celestial)")]
        [TestCase(CreatureConstants.PurpleWorm, "Purple worm")]
        [TestCase(CreatureConstants.Pyrohydra, "Pyrohydra")]
        [TestCase(CreatureConstants.Quasit, "Quasit (demon)")]
        [TestCase(CreatureConstants.Rat_Dire, "Dire rat")]
        [TestCase(CreatureConstants.RustMonster, "Rust monster")]
        [TestCase(CreatureConstants.Salamander_Average, "Average salamander")]
        [TestCase(CreatureConstants.Salamander_Flamebrother, "Flamebrother salamander")]
        [TestCase(CreatureConstants.Salamander_Noble, "Noble salamander")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Colossal, "Colossal monstrous scorpion")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium, "Medium monstrous scorpion")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small, "Small monstrous scorpion")]
        [TestCase(CreatureConstants.ShockerLizard, "Shocker lizard")]
        [TestCase(CreatureConstants.Shrieker, "Shrieker")]
        [TestCase(CreatureConstants.Skeleton, "Skeleton")]
        [TestCase(CreatureConstants.Skeleton_Giant, "Giant skeleton")]
        [TestCase(CreatureConstants.Skeleton_HumanWarrior, "Human warrior skeleton")]
        [TestCase(CreatureConstants.Slaad_Death, "Death slaad")]
        [TestCase(CreatureConstants.Slaad_Green, "Green slaad")]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, "Giant constrictor snake")]
        [TestCase(CreatureConstants.Snake_Viper_Huge, "Huge viper snake")]
        [TestCase(CreatureConstants.Snake_Viper_Tiny, "Tiny viper snake")]
        [TestCase(CreatureConstants.Solar, "Solar (celestial)")]
        [TestCase(CreatureConstants.Spider_Monstrous_Huge, "Huge monstrous spider")]
        [TestCase(CreatureConstants.Spider_Monstrous_Medium, "Medium monstrous spider")]
        [TestCase(CreatureConstants.Spider_Monstrous_Small, "Small monstrous spider")]
        [TestCase(CreatureConstants.SpiderEater, "Spider eater")]
        [TestCase(CreatureConstants.Stirge, "Stirge")]
        [TestCase(CreatureConstants.Troglodyte, "Troglodyte")]
        [TestCase(CreatureConstants.Vampire, "Vampire")]
        [TestCase(CreatureConstants.VampireSpawn, "Vampire spawn")]
        [TestCase(CreatureConstants.VioletFungus, "Violet fungus")]
        [TestCase(CreatureConstants.Vrock, "Vrock (demon)")]
        [TestCase(CreatureConstants.Weasel_Dire, "Dire weasel")]
        [TestCase(CreatureConstants.Wererat, "Wererat")]
        [TestCase(CreatureConstants.Wight, "Wight")]
        [TestCase(CreatureConstants.Wolverine_Dire, "Dire wolverine")]
        [TestCase(CreatureConstants.Worg, "Worg")]
        [TestCase(CreatureConstants.Wraith, "Wraith")]
        [TestCase(CreatureConstants.Yrthak, "Yrthak")]
        [TestCase(CreatureConstants.Zombie, "Zombie")]
        [TestCase(CreatureConstants.Zombie_HumanCommoner, "Human commoner zombie")]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan, "Gargantuan animated object")]
        [TestCase(CreatureConstants.Barbazu, "Barbazu (devil)")]
        [TestCase(CreatureConstants.Belker, "Belker")]
        [TestCase(CreatureConstants.ChaosBeast, "Chaos beast")]
        [TestCase(CreatureConstants.Chimera, "Chimera")]
        [TestCase(CreatureConstants.Deinonychus, "Deinonychus")]
        [TestCase(CreatureConstants.Bat_Dire, "Dire bat")]
        [TestCase(CreatureConstants.Bear_Dire, "Dire bear")]
        [TestCase(CreatureConstants.Dragonne, "Dragonne")]
        [TestCase(CreatureConstants.Elemental_Air_Huge, "Huge air elemental")]
        [TestCase(CreatureConstants.Elemental_Earth_Huge, "Huge earth elemental")]
        [TestCase(CreatureConstants.Elemental_Fire_Huge, "Huge fire elemental")]
        [TestCase(CreatureConstants.Elemental_Water_Huge, "Huge water elemental")]
        [TestCase(CreatureConstants.FormianTaskmaster, "Formian taskmaster")]
        [TestCase(CreatureConstants.Bee_Giant, "Giant bee")]
        [TestCase(CreatureConstants.Owl_Giant, "Giant owl")]
        [TestCase(CreatureConstants.Golem_Flesh, "Flesh golem")]
        [TestCase(CreatureConstants.Hellcat, "Hellcat")]
        [TestCase(CreatureConstants.Giant_Hill, "Hill giant")]
        [TestCase(CreatureConstants.HoundArchon, "Hound archon")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge, "Huge monstrous scorpion")]
        [TestCase(CreatureConstants.Janni, "Janni")]
        [TestCase(CreatureConstants.Lamia, "Lamia")]
        [TestCase(CreatureConstants.Lillend, "Lillend")]
        [TestCase(CreatureConstants.Medusa, "Medusa")]
        [TestCase(CreatureConstants.Megaraptor, "Megaraptor")]
        [TestCase(CreatureConstants.Nymph, "Nymph")]
        [TestCase(CreatureConstants.Phasm, "Phasm")]
        [TestCase(CreatureConstants.Slaad_Red, "Red slaad")]
        [TestCase(CreatureConstants.Spectre, "Spectre")]
        [TestCase(CreatureConstants.Succubus, "Succubus (demon)")]
        [TestCase(CreatureConstants.Werewolf, "Werewolf")]
        [TestCase(CreatureConstants.Wolf, "Wolf")]
        [TestCase(CreatureConstants.Wyvern, "Wyvern")]
        [TestCase(CreatureConstants.Xorn_Average, "Average xorn")]
        [TestCase(CreatureConstants.CelestialCreature, "Celestial creature")]
        [TestCase(CreatureConstants.FiendishCreature, "Fiendish creature")]
        public void Constant(string constant, string value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }
    }
}
