using EncounterGen.Common;
using NUnit.Framework;

namespace EncounterGen.Tests.Unit.Common
{
    [TestFixture]
    public class CreatureConstantsTests
    {
        [TestCase(CreatureConstants.Allip, "Allip")]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan, "Gargantuan animated object")]
        [TestCase(CreatureConstants.AnimatedObject_Medium, "Medium animated object")]
        [TestCase(CreatureConstants.AnimatedObject_Small, "Small animated object")]
        [TestCase(CreatureConstants.AnimatedObject_Tiny, "Tiny animated object")]
        [TestCase(CreatureConstants.Ankheg, "Ankheg")]
        [TestCase(CreatureConstants.Annis, "Annis (hag)")]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, "Giant soldier ant")]
        [TestCase(CreatureConstants.Ant_Giant_Worker, "Giant worker ant")]
        [TestCase(CreatureConstants.Ape, "Ape")]
        [TestCase(CreatureConstants.Ape_Dire, "Dire ape")]
        [TestCase(CreatureConstants.Aranea, "Aranea")]
        [TestCase(CreatureConstants.Arrowhawk_Adult, "Adult arrowhawk")]
        [TestCase(CreatureConstants.Arrowhawk_Elder, "Elder arrowhawk")]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, "Juvenile arrowhawk")]
        [TestCase(CreatureConstants.AstralDeva, "Astral deva (celestial)")]
        [TestCase(CreatureConstants.Azer, "Azer")]
        [TestCase(CreatureConstants.Baboon, "Baboon")]
        [TestCase(CreatureConstants.Badger_Dire, "Dire badger")]
        [TestCase(CreatureConstants.Balor, "Balor (demon)")]
        [TestCase(CreatureConstants.Barbazu, "Barbazu (devil)")]
        [TestCase(CreatureConstants.Barghest, "Barghest")]
        [TestCase(CreatureConstants.Bat, "Bat")]
        [TestCase(CreatureConstants.Bat_Dire, "Dire bat")]
        [TestCase(CreatureConstants.Bear_Black, "Black bear")]
        [TestCase(CreatureConstants.Bear_Brown, "Brown bear")]
        [TestCase(CreatureConstants.Bear_Dire, "Dire bear")]
        [TestCase(CreatureConstants.Bear_Polar, "Polar bear")]
        [TestCase(CreatureConstants.Bee_Giant, "Giant bee")]
        [TestCase(CreatureConstants.Behir, "Behir")]
        [TestCase(CreatureConstants.Beholder, "Beholder")]
        [TestCase(CreatureConstants.Belker, "Belker")]
        [TestCase(CreatureConstants.BlinkDog, "Blink dog")]
        [TestCase(CreatureConstants.Boar, "Boar")]
        [TestCase(CreatureConstants.Boar_Dire, "Dire boar")]
        [TestCase(CreatureConstants.Bodak, "Bodak")]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, "Giant bombardier beetle")]
        [TestCase(CreatureConstants.Bugbear, "Bugbear")]
        [TestCase(CreatureConstants.CarrionCrawler, "Carrion crawler")]
        [TestCase(CreatureConstants.CelestialCreature, "Celestial creature")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, "Gargantuan monstrous centipede")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, "Huge monstrous centipede")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, "Large monstrous centipede")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, "Medium monstrous centipede")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, "Small monstrous centipede")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, "Tiny monstrous centipede")]
        [TestCase(CreatureConstants.ChaosBeast, "Chaos beast")]
        [TestCase(CreatureConstants.Character, "Character")]
        [TestCase(CreatureConstants.Chimera, "Chimera")]
        [TestCase(CreatureConstants.Choker, "Choker")]
        [TestCase(CreatureConstants.Chuul, "Chuul")]
        [TestCase(CreatureConstants.Cockatrice, "Cockatrice")]
        [TestCase(CreatureConstants.Commoner_Farmer, "Commoner (Farmer)")]
        [TestCase(CreatureConstants.Commoner_Herder, "Commoner (Herder)")]
        [TestCase(CreatureConstants.Commoner_Hunter, "Commoner (Hunter)")]
        [TestCase(CreatureConstants.Commoner_Merchant, "Commoner (Merchant)")]
        [TestCase(CreatureConstants.Commoner_Minstrel, "Commoner (Minstrel)")]
        [TestCase(CreatureConstants.Commoner_Pilgrim, "Commoner (Pilgrim)")]
        [TestCase(CreatureConstants.Cornugon, "Cornugon (devil)")]
        [TestCase(CreatureConstants.Crocodile, "Crocodile")]
        [TestCase(CreatureConstants.Cryohydra, "Cryohydra")]
        [TestCase(CreatureConstants.Darkmantle, "Darkmantle")]
        [TestCase(CreatureConstants.Deinonychus, "Deinonychus")]
        [TestCase(CreatureConstants.Devourer, "Devourer")]
        [TestCase(CreatureConstants.Digester, "Digester")]
        [TestCase(CreatureConstants.Djinn, "Djinn")]
        [TestCase(CreatureConstants.Djinn_Noble, "Noble djinn")]
        [TestCase(CreatureConstants.Dog, "Dog")]
        [TestCase(CreatureConstants.Doppelganger, "Doppelganger")]
        [TestCase(CreatureConstants.Dragon, "Dragon")]
        [TestCase(CreatureConstants.Dragon_Black_VeryOld, "Very old black dragon")]
        [TestCase(CreatureConstants.Dragonne, "Dragonne")]
        [TestCase(CreatureConstants.Dretch, "Dretch (demon)")]
        [TestCase(CreatureConstants.DwarfWarrior, "Dwarf warrior")]
        [TestCase(CreatureConstants.Eagle_Giant, "Giant eagle")]
        [TestCase(CreatureConstants.Efreet, "Efreet")]
        [TestCase(CreatureConstants.Elemental_Air_Elder, "Elder air elemental")]
        [TestCase(CreatureConstants.Elemental_Air_Huge, "Huge air elemental")]
        [TestCase(CreatureConstants.Elemental_Air_Small, "Small air elemental")]
        [TestCase(CreatureConstants.Elemental_Earth_Elder, "Elder earth elemental")]
        [TestCase(CreatureConstants.Elemental_Earth_Small, "Small earth elemental")]
        [TestCase(CreatureConstants.Elemental_Earth_Huge, "Huge earth elemental")]
        [TestCase(CreatureConstants.Elemental_Fire_Elder, "Elder fire elemental")]
        [TestCase(CreatureConstants.Elemental_Fire_Huge, "Huge fire elemental")]
        [TestCase(CreatureConstants.Elemental_Fire_Small, "Small fire elemental")]
        [TestCase(CreatureConstants.Elemental_Water_Elder, "Elder water elemental")]
        [TestCase(CreatureConstants.Elemental_Water_Huge, "Huge water elemental")]
        [TestCase(CreatureConstants.Elemental_Water_Small, "Small water elemental")]
        [TestCase(CreatureConstants.ElfWarrior, "Elf warrior")]
        [TestCase(CreatureConstants.Erinyes, "Erinyes (devil)")]
        [TestCase(CreatureConstants.EtherealMarauder, "Ethereal marauder")]
        [TestCase(CreatureConstants.Ettercap, "Ettercap")]
        [TestCase(CreatureConstants.Ettin, "Ettin")]
        [TestCase(CreatureConstants.Expert_Merchant, "Expert (Merchant)")]
        [TestCase(CreatureConstants.Expert_Minstrel, "Expert (Minstrel)")]
        [TestCase(CreatureConstants.FiendishCreature, "Fiendish creature")]
        [TestCase(CreatureConstants.FireBeetle_Giant, "Giant fire beetle")]
        [TestCase(CreatureConstants.FormianTaskmaster, "Formian taskmaster")]
        [TestCase(CreatureConstants.FormianWarrior, "Formian warrior")]
        [TestCase(CreatureConstants.FormianWorker, "Formian worker")]
        [TestCase(CreatureConstants.Gargoyle, "Gargoyle")]
        [TestCase(CreatureConstants.Gelugon, "Gelugon (devil)")]
        [TestCase(CreatureConstants.Ghaele, "Ghaele (celestial)")]
        [TestCase(CreatureConstants.Ghast, "Ghast")]
        [TestCase(CreatureConstants.Ghost, "Ghost")]
        [TestCase(CreatureConstants.Ghoul, "Ghoul")]
        [TestCase(CreatureConstants.Giant_Cloud, "Cloud giant")]
        [TestCase(CreatureConstants.Giant_Frost, "Frost giant")]
        [TestCase(CreatureConstants.Giant_Hill, "Hill giant")]
        [TestCase(CreatureConstants.Giant_Stone, "Stone giant")]
        [TestCase(CreatureConstants.Giant_Storm, "Storm giant")]
        [TestCase(CreatureConstants.GibberingMouther, "Gibbering mouther")]
        [TestCase(CreatureConstants.Glabrezu, "Glabrezu (demon)")]
        [TestCase(CreatureConstants.Gnoll, "Gnoll")]
        [TestCase(CreatureConstants.Goblin, "Goblin")]
        [TestCase(CreatureConstants.Golem_Flesh, "Flesh golem")]
        [TestCase(CreatureConstants.Golem_Stone, "Stone golem")]
        [TestCase(CreatureConstants.Golem_Stone_Greater, "Greater stone golem")]
        [TestCase(CreatureConstants.Gorgon, "Gorgon")]
        [TestCase(CreatureConstants.GrayRender, "Gray render")]
        [TestCase(CreatureConstants.GreenHag, "Green hag (hag)")]
        [TestCase(CreatureConstants.Grick, "Grick")]
        [TestCase(CreatureConstants.Hamatula, "Hamatula (devil)")]
        [TestCase(CreatureConstants.Hellcat, "Hellcat")]
        [TestCase(CreatureConstants.HellHound, "Hell hound")]
        [TestCase(CreatureConstants.Hezrou, "Hezrou (demon)")]
        [TestCase(CreatureConstants.Hobgoblin, "Hobgoblin")]
        [TestCase(CreatureConstants.Homunculus, "Homunculus")]
        [TestCase(CreatureConstants.HoundArchon, "Hound archon")]
        [TestCase(CreatureConstants.Howler, "Howler")]
        [TestCase(CreatureConstants.Human, "Human")]
        [TestCase(CreatureConstants.Hydra, "Hydra")]
        [TestCase(CreatureConstants.Hyena, "Hyena")]
        [TestCase(CreatureConstants.Imp, "Imp (devil)")]
        [TestCase(CreatureConstants.Janni, "Janni")]
        [TestCase(CreatureConstants.Kobold, "Kobold")]
        [TestCase(CreatureConstants.Krenshar, "Krenshar")]
        [TestCase(CreatureConstants.Kyton, "Kyton (devil)")]
        [TestCase(CreatureConstants.Lamia, "Lamia")]
        [TestCase(CreatureConstants.Lammasu, "Lammasu")]
        [TestCase(CreatureConstants.LanternArchon, "Lantern archon (celestial)")]
        [TestCase(CreatureConstants.Lemure, "Lemure (devil)")]
        [TestCase(CreatureConstants.Leopard, "Leopard")]
        [TestCase(CreatureConstants.Lich, "Lich")]
        [TestCase(CreatureConstants.Lillend, "Lillend")]
        [TestCase(CreatureConstants.Lion_Dire, "Dire lion")]
        [TestCase(CreatureConstants.Livestock, "Livestock")]
        [TestCase(CreatureConstants.Lizard_Monitor, "Monitor lizard")]
        [TestCase(CreatureConstants.Lizardfolk, "Lizardfolk")]
        [TestCase(CreatureConstants.Magmin, "Magmin")]
        [TestCase(CreatureConstants.Manticore, "Manticore")]
        [TestCase(CreatureConstants.Marilith, "Marilith (demon)")]
        [TestCase(CreatureConstants.Medusa, "Medusa")]
        [TestCase(CreatureConstants.Megaraptor, "Megaraptor")]
        [TestCase(CreatureConstants.Mephit, "Mephit")]
        [TestCase(CreatureConstants.Mimic, "Mimic")]
        [TestCase(CreatureConstants.MindFlayer, "Mind flayer")]
        [TestCase(CreatureConstants.Mohrg, "Mohrg")]
        [TestCase(CreatureConstants.Mummy, "Mummy")]
        [TestCase(CreatureConstants.Naga_Dark, "Dark naga")]
        [TestCase(CreatureConstants.Naga_Spirit, "Spirit naga")]
        [TestCase(CreatureConstants.Nalfeshnee, "Nalfeshnee (demon)")]
        [TestCase(CreatureConstants.Nightcrawler, "Nightcrawler (nightshade)")]
        [TestCase(CreatureConstants.Nightmare, "Nightmare")]
        [TestCase(CreatureConstants.Nightwalker, "Nightwalker (nightshade)")]
        [TestCase(CreatureConstants.Nightwing, "Nightwing (nightshade)")]
        [TestCase(CreatureConstants.NPC, "NPC")]
        [TestCase(CreatureConstants.NPC_Traveler, "NPC (Traveler)")]
        [TestCase(CreatureConstants.Nymph, "Nymph")]
        [TestCase(CreatureConstants.Ogre, "Ogre")]
        [TestCase(CreatureConstants.OgreMage, "Ogre mage")]
        [TestCase(CreatureConstants.Ooze_Gray, "Gray ooze")]
        [TestCase(CreatureConstants.Ooze_OchreJelly, "Ochre jelly")]
        [TestCase(CreatureConstants.Orc, "Orc")]
        [TestCase(CreatureConstants.Osyluth, "Osyluth (devil)")]
        [TestCase(CreatureConstants.Owl_Giant, "Giant owl")]
        [TestCase(CreatureConstants.Phasm, "Phasm")]
        [TestCase(CreatureConstants.PitFiend, "Pit fiend (devil)")]
        [TestCase(CreatureConstants.Planetar, "Planetar (celestial)")]
        [TestCase(CreatureConstants.Pseudodragon, "Pseudodragon")]
        [TestCase(CreatureConstants.PurpleWorm, "Purple worm")]
        [TestCase(CreatureConstants.Pyrohydra, "Pyrohydra")]
        [TestCase(CreatureConstants.Quasit, "Quasit (demon)")]
        [TestCase(CreatureConstants.Rat_Dire, "Dire rat")]
        [TestCase(CreatureConstants.RustMonster, "Rust monster")]
        [TestCase(CreatureConstants.Salamander_Average, "Average salamander")]
        [TestCase(CreatureConstants.Salamander_Flamebrother, "Flamebrother salamander")]
        [TestCase(CreatureConstants.Salamander_Noble, "Noble salamander")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Colossal, "Colossal monstrous scorpion")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge, "Huge monstrous scorpion")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Large, "Large monstrous scorpion")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium, "Medium monstrous scorpion")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small, "Small monstrous scorpion")]
        [TestCase(CreatureConstants.SeaHag, "Sea hag (hag)")]
        [TestCase(CreatureConstants.ShadowMastiff, "Shadow mastiff")]
        [TestCase(CreatureConstants.ShockerLizard, "Shocker lizard")]
        [TestCase(CreatureConstants.Shrieker, "Shrieker")]
        [TestCase(CreatureConstants.Skeleton, "Skeleton")]
        [TestCase(CreatureConstants.Skeleton_Giant, "Giant skeleton")]
        [TestCase(CreatureConstants.Skeleton_HumanWarrior, "Human warrior skeleton")]
        [TestCase(CreatureConstants.Slaad_Blue, "Blue slaad")]
        [TestCase(CreatureConstants.Slaad_Death, "Death slaad")]
        [TestCase(CreatureConstants.Slaad_Gray, "Gray slaad")]
        [TestCase(CreatureConstants.Slaad_Green, "Green slaad")]
        [TestCase(CreatureConstants.Slaad_Red, "Red slaad")]
        [TestCase(CreatureConstants.Snake_Constrictor, "Constrictor snake")]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, "Giant constrictor snake")]
        [TestCase(CreatureConstants.Snake_Viper_Huge, "Huge viper snake")]
        [TestCase(CreatureConstants.Snake_Viper_Large, "Large viper snake")]
        [TestCase(CreatureConstants.Snake_Viper_Small, "Small viper snake")]
        [TestCase(CreatureConstants.Snake_Viper_Tiny, "Tiny viper snake")]
        [TestCase(CreatureConstants.Solar, "Solar (celestial)")]
        [TestCase(CreatureConstants.Spectre, "Spectre")]
        [TestCase(CreatureConstants.Spider_Monstrous_Gargantuan, "Gargantuan monstrous spider")]
        [TestCase(CreatureConstants.Spider_Monstrous_Huge, "Huge monstrous spider")]
        [TestCase(CreatureConstants.Spider_Monstrous_Large, "Large monstrous spider")]
        [TestCase(CreatureConstants.Spider_Monstrous_Medium, "Medium monstrous spider")]
        [TestCase(CreatureConstants.Spider_Monstrous_Small, "Small monstrous spider")]
        [TestCase(CreatureConstants.Spider_Monstrous_Tiny, "Tiny monstrous spider")]
        [TestCase(CreatureConstants.SpiderEater, "Spider eater")]
        [TestCase(CreatureConstants.StagBeetle_Giant, "Giant stag beetle")]
        [TestCase(CreatureConstants.Stirge, "Stirge")]
        [TestCase(CreatureConstants.Succubus, "Succubus (demon)")]
        [TestCase(CreatureConstants.Tarrasque, "Tarrasque")]
        [TestCase(CreatureConstants.Tendriculos, "Tendriculos")]
        [TestCase(CreatureConstants.Thoqqua, "Thoqqua")]
        [TestCase(CreatureConstants.Tiger, "Tiger")]
        [TestCase(CreatureConstants.Tiger_Dire, "Dire tiger")]
        [TestCase(CreatureConstants.Treant, "Treant")]
        [TestCase(CreatureConstants.Troglodyte, "Troglodyte")]
        [TestCase(CreatureConstants.Troll, "Troll")]
        [TestCase(CreatureConstants.TrumpetArchon, "Trumpet archon")]
        [TestCase(CreatureConstants.Tyrannosaurus, "Tyrannosaurus")]
        [TestCase(CreatureConstants.Vampire, "Vampire")]
        [TestCase(CreatureConstants.VampireSpawn, "Vampire spawn")]
        [TestCase(CreatureConstants.Vargouille, "Vargouille")]
        [TestCase(CreatureConstants.VioletFungus, "Violet fungus")]
        [TestCase(CreatureConstants.Vrock, "Vrock (demon)")]
        [TestCase(CreatureConstants.Warrior_Bandit, "Warrior (Bandit)")]
        [TestCase(CreatureConstants.Warrior_BanditLeader, "Warrior (Bandit Leader)")]
        [TestCase(CreatureConstants.Warrior_Captain, "Warrior (Captain)")]
        [TestCase(CreatureConstants.Warrior_Guard, "Warrior (Guard)")]
        [TestCase(CreatureConstants.Warrior_Hunter, "Warrior (Hunter)")]
        [TestCase(CreatureConstants.Warrior_Patrol, "Warrior (Patrol)")]
        [TestCase(CreatureConstants.Wasp_Giant, "Giant wasp")]
        [TestCase(CreatureConstants.Weasel_Dire, "Dire weasel")]
        [TestCase(CreatureConstants.Werebear, "Werebear")]
        [TestCase(CreatureConstants.Wereboar, "Wereboar")]
        [TestCase(CreatureConstants.Wererat, "Wererat")]
        [TestCase(CreatureConstants.Weretiger, "Weretiger")]
        [TestCase(CreatureConstants.Werewolf, "Werewolf")]
        [TestCase(CreatureConstants.Wight, "Wight")]
        [TestCase(CreatureConstants.Wolf, "Wolf")]
        [TestCase(CreatureConstants.Wolf_Dire, "Dire wolf")]
        [TestCase(CreatureConstants.Wolverine_Dire, "Dire wolverine")]
        [TestCase(CreatureConstants.Worg, "Worg")]
        [TestCase(CreatureConstants.Wraith, "Wraith")]
        [TestCase(CreatureConstants.Wraith_Dread, "Dread wraith")]
        [TestCase(CreatureConstants.Wyvern, "Wyvern")]
        [TestCase(CreatureConstants.Xill, "Xill")]
        [TestCase(CreatureConstants.Xorn_Average, "Average xorn")]
        [TestCase(CreatureConstants.Xorn_Elder, "Elder xorn")]
        [TestCase(CreatureConstants.Xorn_Minor, "Minor xorn")]
        [TestCase(CreatureConstants.YethHound, "Yeth hound")]
        [TestCase(CreatureConstants.Yrthak, "Yrthak")]
        [TestCase(CreatureConstants.Zombie, "Zombie")]
        [TestCase(CreatureConstants.Zombie_HumanCommoner, "Human commoner zombie")]
        public void Constant(string constant, string value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }
    }
}
