using EncounterGen.Common;
using EncounterGen.Tables;
using NUnit.Framework;
using System;

namespace EncounterGen.Tests.Integration.Tables.Treasures
{
    [TestFixture]
    public class TreasureAdjustmentTests : CollectionTests
    {
        protected override String tableName
        {
            get
            {
                return TableNameConstants.TreasureAdjustment;
            }
        }

        [Test]
        public override void EntriesAreComplete()
        {
            var entries = new[]
            {
                CreatureConstants.Allip,
                CreatureConstants.Ankheg,
                CreatureConstants.Ant_Giant,
                CreatureConstants.Ant_Giant_Soldier,
                CreatureConstants.Ant_Giant_Worker,
                CreatureConstants.AstralDeva,
                CreatureConstants.Azer,
                CreatureConstants.Balor,
                CreatureConstants.Beholder,
                CreatureConstants.BlinkDog,
                CreatureConstants.Boar_Dire,
                CreatureConstants.Bugbear,
                CreatureConstants.CarrionCrawler,
                CreatureConstants.Centipede_Monstrous_Large,
                CreatureConstants.Centipede_Monstrous_Medium,
                CreatureConstants.Character,
                CreatureConstants.Choker,
                CreatureConstants.Cockatrice,
                CreatureConstants.Cornugon,
                CreatureConstants.Cryohydra,
                CreatureConstants.Darkmantle,
                CreatureConstants.Doppelganger,
                CreatureConstants.Dragon,
                CreatureConstants.DwarfWarrior,
                CreatureConstants.ElfWarrior,
                CreatureConstants.EtherealMarauder,
                CreatureConstants.Ettercap,
                CreatureConstants.FireBeetle_Giant,
                CreatureConstants.FormianWarrior,
                CreatureConstants.FormianWorker,
                CreatureConstants.Gelugon,
                CreatureConstants.Ghaeles,
                CreatureConstants.Ghast,
                CreatureConstants.Ghost,
                CreatureConstants.Ghoul,
                CreatureConstants.Giant_Cloud,
                CreatureConstants.Giant_Frost,
                CreatureConstants.Giant_Storm,
                CreatureConstants.GibberingMouther,
                CreatureConstants.Glabrezu,
                CreatureConstants.Gnoll,
                CreatureConstants.Goblin,
                CreatureConstants.Golem_Stone,
                CreatureConstants.Greenhag,
                CreatureConstants.Grick,
                CreatureConstants.Hamatula,
                CreatureConstants.Hezrou,
                CreatureConstants.Hobgoblin,
                CreatureConstants.Hydra,
                CreatureConstants.Hyena,
                CreatureConstants.Imp,
                CreatureConstants.Kobold,
                CreatureConstants.Krenshar,
                CreatureConstants.LanternArchon,
                CreatureConstants.Lemure,
                CreatureConstants.Lich,
                CreatureConstants.Lion_Dire,
                CreatureConstants.Lizardfolk,
                CreatureConstants.Lizard_Giant,
                CreatureConstants.Magmin,
                CreatureConstants.Marilith,
                CreatureConstants.Mephit,
                CreatureConstants.Mimic,
                CreatureConstants.MindFlayer,
                CreatureConstants.Mummy,
                CreatureConstants.Naga_Spirit,
                CreatureConstants.Nalfeshnee,
                CreatureConstants.Nightcrawler,
                CreatureConstants.Nightmare,
                CreatureConstants.Nightwalker,
                CreatureConstants.OchreJelly,
                CreatureConstants.Ogre,
                CreatureConstants.Ooze_Gray,
                CreatureConstants.Orc,
                CreatureConstants.PitFiend,
                CreatureConstants.Planetar,
                CreatureConstants.PurpleWorm,
                CreatureConstants.Pyrohydra,
                CreatureConstants.Rat_Dire,
                CreatureConstants.RustMonster,
                CreatureConstants.Salamander_Large,
                CreatureConstants.Salamander_Small,
                CreatureConstants.Scorpion_Monstrous_Colossal,
                CreatureConstants.Scorpion_Monstrous_Medium,
                CreatureConstants.Scorpion_Monstrous_Small,
                CreatureConstants.ShockerLizard,
                CreatureConstants.Shrieker,
                CreatureConstants.Skeleton_Giant,
                CreatureConstants.Skeleton_HumanWarrior,
                CreatureConstants.Slaadi_Death,
                CreatureConstants.Slaadi_Green,
                CreatureConstants.Snake_Constrictor_Giant,
                CreatureConstants.Snake_Viper_Huge,
                CreatureConstants.Snake_Viper_Tiny,
                CreatureConstants.Solar,
                CreatureConstants.SpiderEater,
                CreatureConstants.Spider_Monstrous_Huge,
                CreatureConstants.Spider_Monstrous_Medium,
                CreatureConstants.Spider_Monstrous_Small,
                CreatureConstants.Stirge,
                CreatureConstants.Troglodyte,
                CreatureConstants.VampireSpawn,
                CreatureConstants.Vampire,
                CreatureConstants.VioletFungus,
                CreatureConstants.Vrock,
                CreatureConstants.Weasel_Dire,
                CreatureConstants.Wererat,
                CreatureConstants.Wight,
                CreatureConstants.Wolverine_Dire,
                CreatureConstants.Worg,
                CreatureConstants.Wraith,
                CreatureConstants.Yrthak,
                CreatureConstants.Zombie_HumanCommoner
            };

            AssertEntriesAreComplete(entries);
        }


        [TestCase(CreatureConstants.Allip, 0)]
        [TestCase(CreatureConstants.Ankheg, 0)]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, 0)]
        [TestCase(CreatureConstants.Ant_Giant_Worker, 0)]
        [TestCase(CreatureConstants.AstralDeva, 0, 2, 1)]
        [TestCase(CreatureConstants.Azer,)]
        [TestCase(CreatureConstants.Balor,)]
        [TestCase(CreatureConstants.Beholder,)]
        [TestCase(CreatureConstants.BlinkDog,)]
        [TestCase(CreatureConstants.Boar_Dire,)]
        [TestCase(CreatureConstants.Bugbear,)]
        [TestCase(CreatureConstants.CarrionCrawler,)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large,)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium,)]
        [TestCase(CreatureConstants.Character,)]
        [TestCase(CreatureConstants.Choker,)]
        [TestCase(CreatureConstants.Cockatrice,)]
        [TestCase(CreatureConstants.Cornugon,)]
        [TestCase(CreatureConstants.Cryohydra,)]
        [TestCase(CreatureConstants.Darkmantle,)]
        [TestCase(CreatureConstants.Doppelganger,)]
        [TestCase(CreatureConstants.Dragon,)]
        [TestCase(CreatureConstants.DwarfWarrior,)]
        [TestCase(CreatureConstants.ElfWarrior,)]
        [TestCase(CreatureConstants.EtherealMarauder,)]
        [TestCase(CreatureConstants.Ettercap,)]
        [TestCase(CreatureConstants.FireBeetle_Giant,)]
        [TestCase(CreatureConstants.FormianWarrior,)]
        [TestCase(CreatureConstants.FormianWorker,)]
        [TestCase(CreatureConstants.Gelugon,)]
        [TestCase(CreatureConstants.Ghaeles,)]
        [TestCase(CreatureConstants.Ghast,)]
        [TestCase(CreatureConstants.Ghost,)]
        [TestCase(CreatureConstants.Ghoul,)]
        [TestCase(CreatureConstants.Giant_Cloud,)]
        [TestCase(CreatureConstants.Giant_Frost,)]
        [TestCase(CreatureConstants.Giant_Storm,)]
        [TestCase(CreatureConstants.GibberingMouther,)]
        [TestCase(CreatureConstants.Glabrezu,)]
        [TestCase(CreatureConstants.Gnoll,)]
        [TestCase(CreatureConstants.Goblin,)]
        [TestCase(CreatureConstants.Golem_Stone,)]
        [TestCase(CreatureConstants.Greenhag,)]
        [TestCase(CreatureConstants.Grick,)]
        [TestCase(CreatureConstants.Hamatula,)]
        [TestCase(CreatureConstants.Hezrou,)]
        [TestCase(CreatureConstants.Hobgoblin,)]
        [TestCase(CreatureConstants.Hydra,)]
        [TestCase(CreatureConstants.Hyena,)]
        [TestCase(CreatureConstants.Imp,)]
        [TestCase(CreatureConstants.Kobold,)]
        [TestCase(CreatureConstants.Krenshar,)]
        [TestCase(CreatureConstants.LanternArchon,)]
        [TestCase(CreatureConstants.Lemure,)]
        [TestCase(CreatureConstants.Lich,)]
        [TestCase(CreatureConstants.Lion_Dire,)]
        [TestCase(CreatureConstants.Lizardfolk,)]
        [TestCase(CreatureConstants.Lizard_Giant,)]
        [TestCase(CreatureConstants.Magmin,)]
        [TestCase(CreatureConstants.Marilith,)]
        [TestCase(CreatureConstants.Mephit,)]
        [TestCase(CreatureConstants.Mimic,)]
        [TestCase(CreatureConstants.MindFlayer,)]
        [TestCase(CreatureConstants.Mummy,)]
        [TestCase(CreatureConstants.Naga_Spirit,)]
        [TestCase(CreatureConstants.Nalfeshnee,)]
        [TestCase(CreatureConstants.Nightcrawler,)]
        [TestCase(CreatureConstants.Nightmare,)]
        [TestCase(CreatureConstants.Nightwalker,)]
        [TestCase(CreatureConstants.OchreJelly,)]
        [TestCase(CreatureConstants.Ogre,)]
        [TestCase(CreatureConstants.Ooze_Gray,)]
        [TestCase(CreatureConstants.Orc,)]
        [TestCase(CreatureConstants.PitFiend,)]
        [TestCase(CreatureConstants.Planetar,)]
        [TestCase(CreatureConstants.PurpleWorm,)]
        [TestCase(CreatureConstants.Pyrohydra,)]
        [TestCase(CreatureConstants.Rat_Dire,)]
        [TestCase(CreatureConstants.RustMonster,)]
        [TestCase(CreatureConstants.Salamander_Large,)]
        [TestCase(CreatureConstants.Salamander_Small,)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Colossal,)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium,)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small,)]
        [TestCase(CreatureConstants.ShockerLizard,)]
        [TestCase(CreatureConstants.Shrieker,)]
        [TestCase(CreatureConstants.Skeleton_Giant,)]
        [TestCase(CreatureConstants.Skeleton_HumanWarrior,)]
        [TestCase(CreatureConstants.Slaadi_Death,)]
        [TestCase(CreatureConstants.Slaadi_Green,)]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant,)]
        [TestCase(CreatureConstants.Snake_Viper_Huge,)]
        [TestCase(CreatureConstants.Snake_Viper_Tiny,)]
        [TestCase(CreatureConstants.Solar,)]
        [TestCase(CreatureConstants.SpiderEater,)]
        [TestCase(CreatureConstants.Spider_Monstrous_Huge,)]
        [TestCase(CreatureConstants.Spider_Monstrous_Medium,)]
        [TestCase(CreatureConstants.Spider_Monstrous_Small,)]
        [TestCase(CreatureConstants.Stirge,)]
        [TestCase(CreatureConstants.Troglodyte,)]
        [TestCase(CreatureConstants.VampireSpawn,)]
        [TestCase(CreatureConstants.Vampire,)]
        [TestCase(CreatureConstants.VioletFungus,)]
        [TestCase(CreatureConstants.Vrock,)]
        [TestCase(CreatureConstants.Weasel_Dire,)]
        [TestCase(CreatureConstants.Wererat,)]
        [TestCase(CreatureConstants.Wight,)]
        [TestCase(CreatureConstants.Wolverine_Dire,)]
        [TestCase(CreatureConstants.Worg,)]
        [TestCase(CreatureConstants.Wraith,)]
        [TestCase(CreatureConstants.Yrthak,)]
        [TestCase(CreatureConstants.Zombie_HumanCommoner, )]
        public void Adjustment(String entry, Int32 adjustment)
        {
            base.Collection(entry, new[] { adjustment.ToString() });
        }
    }
}
